app/views/__init__.py
"""
__init__.py file of views module with
imported info, employee_view and department_view submodules
Register the user blueprint and specify the logic on '/' and '/home' addresses
Also handle an error status
"""

# pylint: disable=cyclic-import
from flask import Blueprint
from flask import render_template, session

user = Blueprint('user', __name__)
from . import authentification_view
from . import hospital_department_view
from . import employees_view
from . import profile_view

# because the blueprint must be registered before importing the views


@user.route('/')
@user.route('/home')
def home_page():
    """
    Render the home page template on the / route
    """
    return render_template('index.html', session=session)


@user.app_errorhandler(404)
def handle_404(err):
    """
    Handel 404 error and redirect to 404.html page
    """
    return render_template('404.html'), 404


@user.app_errorhandler(401)
def handle_401(err):
    """
    Handel 401 error and redirect to 401.html page
    """
    return render_template('401.html'), 401

app/views/authentification_view.py
"""
This module represents the logic of authentication of user
"""
from flask import render_template, redirect, flash, session, url_for, request
from flask_login import login_user, login_required, logout_user, current_user
from . import user
from . import WTForm
from ..models.admin import Admin
from werkzeug.security import check_password_hash
from app import login_manager
from app.service.admin import get_admin_by_name


@login_manager.user_loader
def load_user(user_id):
    return Admin.query.get(int(user_id))


@user.route('/login', methods=["POST", "GET"])
def login():
    """
    Handle requests to the /login route
    Cretates login page using WTForm using post-requests.
    Admin data contains in MySQL database

    :return: html page
    """
    session.permanent = True
    if current_user.is_authenticated:
        flash('You are already authorized', 'success')
        return redirect(url_for('user.home_page'))
    form = WTForm.LoginForm()
    if form.validate_on_submit():
        root_user = get_admin_by_name(form.username.data)
        if not root_user:
            flash('An error occured. Try to enter correct name of password', 'error')
            return redirect(url_for('user.login'))
        if not check_password_hash(root_user.password, form.password.data):
            flash('An error occured. Try to enter correct name of password', 'error')
            return redirect(url_for('user.login'))
        login_user(root_user)
        session['admin'] = root_user.username
        return redirect(url_for('user.home_page'))
    return render_template('login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    """
    Handle requests to the /logout route
    Allow employee to logout moving to home page.
    """
    logout_user()
    return redirect(request.referrer)

app/views/profile_view.py
"""
This module represents the logic of authentication of user
"""
from flask import render_template, session, make_response, request, flash, redirect, url_for
from flask_login import login_required
from . import user
from ..service.admin import get_avatar, get_admin_by_name, update_avatar, check_if_is_available


@user.route('/profile')
@login_required
def profile():
    """
    Handle requests to the /profile route
    """
    admin_profile = get_admin_by_name(session['admin'])
    return render_template('profile.html', admin_profile=admin_profile)


@user.route('/avatar')
@login_required
def avatar():
    response = make_response(get_avatar(session['admin']))
    response.headers['Content-Type'] = 'image/png'
    return response


@user.route('/upload', methods=["POST", "GET"])
@login_required
def upload():
    if request.method == 'POST':
        file = request.files['file']
        if file and check_if_is_available(file.filename):
            try:
                img = file.read()
                res = update_avatar(img, session['admin'])
                if not res:
                    flash("An error occured while updating avatar. Please try again", "error")
                flash("Avatar is changed successfully", "success")
            except FileNotFoundError as e:
                flash("An error occured. Please try again.", "error")
        else:
            flash("An error occured. This format file is not supported. Use png.", "error")

    return redirect(url_for('user.profile'))

app/templates/401.html
{% extends 'base.html' %}

{% block content %}
    {{ super() }}
    <style>
        body {
            background-image: none
        }
    </style>
    <p class="page_not_found">You are unauthorized. Please, authorize using page <a
            href="{{ url_for('user.login') }}">Login</a>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>
</head>
<body>
{% block content -%}
    {%- block mainmenu -%}
        <ul class="mainmenu">
            <li>HOSPITAL APP</li>
            <li><a href="{{ url_for('user.home_page') }}">Home page</a></li>
            <li><a href="{{ url_for('user.get_department_of_hospital') }}">Hospital</a></li>
            <li><a href="{{ url_for('user.get_employees') }}">Employees</a></li>
            {% if current_user.is_authenticated %}
                <li class="last"><a href="{{ url_for('user.profile') }}">Profile</a></li>
                <li class="last"><a href="{{ url_for('user.logout') }}">Logout</a></li>
            {% else %}
                <li class="last"><a href="{{ url_for('user.login') }}">Login</a></li>
            {% endif %}
        </ul>
    {% endblock mainmenu -%}
    <style>
        body {
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            background-image: url("{{ url_for('static', filename='images/hospital.jpg') }}");
        }
    </style>
{% endblock %}
<div class="footer">
    <ul class="mainmenu">
        <li>
            <button class="first">Get more information</button>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.12.15/dist/sweetalert2.all.min.js"></script>
            <script>
                document.querySelector(".first").addEventListener('click', function () {
                    swal("This is simple web application.\nYou can check and search for departments of hospital and employees." +
                        "\nIf you are admin you can delete, add and change information.");
                });
            </script>
        </li>
        <li class="last" style="color:black"> 2021 - All Right Reserved.</li>
    </ul>
</div>
</body>
</html>

app/templates/index.html
<head>
    <link rel="canonical" href="{{ url_for('user.home_page') }}">
    <meta name="description" content="It's start hospital page">
    <title>Hospital</title>
</head>
{% extends 'base.html' %}

{% block content %}
    {{ super() }}
    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{ cat }}">{{ msg }}</div>
    {% endfor %}
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>
    <link rel="canonical" href="{{ url_for('user.login') }}">
    <meta name="description" content="It's admin page">
    <title>Admin page</title>
</head>
{% extends 'base.html' %}
{% block content %}
    {{ super() }}
    <style>
        body {
            background-image: none
        }
    </style>
    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{ cat }}">{{ msg }}</div>
    {% endfor %}
    <div id="login" class="wnd_dlg_back login_wnd">
        <div class="login">
            <form action="" method="post" class="form-contact">
                {{ form.hidden_tag() }}
                {% for field in form if field.name not in ['csrf_token', 'remember', 'submit'] -%}
                    <p>{{ field.label() }}
                    {% if field.errors %}
                        {{ field(class="invalid") }}
                        <span class="invalid-feedback">
		{% for e in field.errors %}
            {{ e }}
        {% endfor %}
	</span>
                    {% else %}
                        {{ field() }}
                    {% endif %}
                {% endfor %}
                <p>{{ form.submit() }}
            </form>
        </div>
    </div>
    </html>
{% endblock %}

app/templates/profile.html
<head>
    <link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>
    <link rel="canonical" href="{{ url_for('user.profile') }}">
    <meta name="description" content="It's profile page">
    <title>Profile page</title>
</head>
{% extends 'base.html' %}
{% block content %}
    {{ super() }}
    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{ cat }}">{{ msg }}</div>
    {% endfor %}
    <style>
        body {
            background-image: none;
            background-color: lightgray;
        }
    </style>
    <table class="profile_table">
        <tr>
            <td valign="top" style="border:none;">
                <div class="profile-ava"><img src="{{ url_for('user.avatar') }}"></div>
                <div class="profile-load">
                    <form action="{{ url_for('user.upload') }}" method="POST" enctype="multipart/form-data">
                        <p><input type="file" name="file">
                        <p><input type="submit" value="Upload">
                    </form>
                </div>
            </td>
            <td valign="top" class="profile-panel" style="border:none;">
                <p><a href="{{ url_for('user.logout') }}">Logout</a>
                <ul class="profile-info">
                    <li>Your name: {{ admin_profile.full_name }}</li>
                </ul>
                </br>
                </br>
                </br>
                </br>
                <div>
                    <a href="{{ url_for('user.get_department_of_hospital') }}">Change or add
                        department</a>
                </div>
                </br>
                <div>
                    <a href="{{ url_for('user.get_employees') }}">Change or add
                        employees</a>
                </div>
            </td>
        </tr>
    </table>
{% endblock %}